// generated by stringer -type=Format -output=z_gen_format_string.go; DO NOT EDIT

package bpg

import "fmt"

const _Format_name = "FormatGRAYFormat420Format422Format444Format420VideoFormat422VideoFormatMax"

var _Format_index = [...]uint8{10, 19, 28, 37, 51, 65, 74}

func (i Format) String() string {
	if i >= Format(len(_Format_index)) {
		return fmt.Sprintf("Format(%d)", i)
	}
	hi := _Format_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Format_index[i-1]
	}
	return _Format_name[lo:hi]
}
