// generated by stringer -type=ColorSpace -output=z_gen_color_space_string.go; DO NOT EDIT

package bpg

import "fmt"

const _ColorSpace_name = "ColorSpaceYCbCrColorSpaceRGBColorSpaceYCgCoColorSpaceYCbCrBT709ColorSpaceYCbCrBT2020ColorSpaceMax"

var _ColorSpace_index = [...]uint8{0, 15, 28, 43, 63, 84, 97}

func (i ColorSpace) String() string {
	if i+1 >= ColorSpace(len(_ColorSpace_index)) {
		return fmt.Sprintf("ColorSpace(%d)", i)
	}
	return _ColorSpace_name[_ColorSpace_index[i]:_ColorSpace_index[i+1]]
}
