// generated by stringer -type=ExtensionTag -output=z_gen_extension_tag_string.go; DO NOT EDIT

package bpg

import "fmt"

const _ExtensionTag_name = "ExtensionTagEXIFExtensionTagICCPExtensionTagXMPExtensionTagTHUMBNAILExtensionTagAnimControl"

var _ExtensionTag_index = [...]uint8{0, 16, 32, 47, 68, 91}

func (i ExtensionTag) String() string {
	i -= 1
	if i+1 >= ExtensionTag(len(_ExtensionTag_index)) {
		return fmt.Sprintf("ExtensionTag(%d)", i+1)
	}
	return _ExtensionTag_name[_ExtensionTag_index[i]:_ExtensionTag_index[i+1]]
}
