// Copyright 2015 <chaishushan{AT}gmail.com>. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Auto Generated By 'go generate', DONOT EDIT!!!

// +build cgo
// +build !windows

#include "./internal/libbpg-0.9.5/jctvc/TLibEncoder/NALwrite.cpp"
